//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityBase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Resources.EntityBase", typeof(EntityBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主标识符.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string InsertedDateTime {
            get {
                return ResourceManager.GetString("InsertedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间上限.
        /// </summary>
        public static string InsertedDateTimeMax {
            get {
                return ResourceManager.GetString("InsertedDateTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间下限.
        /// </summary>
        public static string InsertedDateTimeMin {
            get {
                return ResourceManager.GetString("InsertedDateTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者Id.
        /// </summary>
        public static string InsertedUserId {
            get {
                return ResourceManager.GetString("InsertedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者名称.
        /// </summary>
        public static string InsertedUserName {
            get {
                return ResourceManager.GetString("InsertedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逻辑删除.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已启用.
        /// </summary>
        public static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改时间.
        /// </summary>
        public static string UpdatedDateTime {
            get {
                return ResourceManager.GetString("UpdatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改时间上限.
        /// </summary>
        public static string UpdatedDateTimeMax {
            get {
                return ResourceManager.GetString("UpdatedDateTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改时间下限.
        /// </summary>
        public static string UpdatedDateTimeMin {
            get {
                return ResourceManager.GetString("UpdatedDateTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者Id.
        /// </summary>
        public static string UpdatedUserId {
            get {
                return ResourceManager.GetString("UpdatedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者名称.
        /// </summary>
        public static string UpdatedUserName {
            get {
                return ResourceManager.GetString("UpdatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者Id长度不能大于{1}.
        /// </summary>
        public static string ValidateInsertedUserIdStringLengthMax {
            get {
                return ResourceManager.GetString("ValidateInsertedUserIdStringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者Id长度不能小于{1}.
        /// </summary>
        public static string ValidateInsertedUserIdStringLengthMin {
            get {
                return ResourceManager.GetString("ValidateInsertedUserIdStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者名称长度不能大于{1}.
        /// </summary>
        public static string ValidateInsertedUserNameStringLengthMax {
            get {
                return ResourceManager.GetString("ValidateInsertedUserNameStringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建者名称长度不能小于{1}.
        /// </summary>
        public static string ValidateInsertedUserNameStringLengthMin {
            get {
                return ResourceManager.GetString("ValidateInsertedUserNameStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者Id长度不能大于{1}.
        /// </summary>
        public static string ValidateUpdatedUserIdStringLengthMax {
            get {
                return ResourceManager.GetString("ValidateUpdatedUserIdStringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者Id长度不能小于{1}.
        /// </summary>
        public static string ValidateUpdatedUserIdStringLengthMin {
            get {
                return ResourceManager.GetString("ValidateUpdatedUserIdStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者名称长度不能大于{1}.
        /// </summary>
        public static string ValidateUpdatedUserNameStringLengthMax {
            get {
                return ResourceManager.GetString("ValidateUpdatedUserNameStringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改者名称长度不能小于{1}.
        /// </summary>
        public static string ValidateUpdatedUserNameStringLengthMin {
            get {
                return ResourceManager.GetString("ValidateUpdatedUserNameStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
