// <auto-generated />
namespace CodeStudy.EntityFrameworkCodeFirst.DataAccess.MigrationsDataAnnotationChapter01
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAnimalTypeTypeNameNotNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAnimalTypeTypeNameNotNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201509270840523_AddAnimalTypeTypeNameNotNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
