//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Resources.CommonLog", typeof(CommonLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Util.Logs.ContextLogger.
        /// </summary>
        public static string ContextKey {
            get {
                return ResourceManager.GetString("ContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务编号.
        /// </summary>
        public static string LogFormatBusinessId {
            get {
                return ResourceManager.GetString("LogFormatBusinessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string LogFormatCaption {
            get {
                return ResourceManager.GetString("LogFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类名.
        /// </summary>
        public static string LogFormatClass {
            get {
                return ResourceManager.GetString("LogFormatClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容：.
        /// </summary>
        public static string LogFormatContent {
            get {
                return ResourceManager.GetString("LogFormatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主机.
        /// </summary>
        public static string LogFormatHost {
            get {
                return ResourceManager.GetString("LogFormatHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string LogFormatIp {
            get {
                return ResourceManager.GetString("LogFormatIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &gt;&gt; .
        /// </summary>
        public static string LogFormatLogLevel {
            get {
                return ResourceManager.GetString("LogFormatLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法.
        /// </summary>
        public static string LogFormatMethod {
            get {
                return ResourceManager.GetString("LogFormatMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作人姓名.
        /// </summary>
        public static string LogFormatOperator {
            get {
                return ResourceManager.GetString("LogFormatOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数.
        /// </summary>
        public static string LogFormatParams {
            get {
                return ResourceManager.GetString("LogFormatParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        public static string LogFormatRole {
            get {
                return ResourceManager.GetString("LogFormatRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql参数.
        /// </summary>
        public static string LogFormatSqlParams {
            get {
                return ResourceManager.GetString("LogFormatSqlParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线程号.
        /// </summary>
        public static string LogFormatThreadId {
            get {
                return ResourceManager.GetString("LogFormatThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作时间.
        /// </summary>
        public static string LogFormatTime {
            get {
                return ResourceManager.GetString("LogFormatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已执行(秒).
        /// </summary>
        public static string LogFormatTotalSeconds {
            get {
                return ResourceManager.GetString("LogFormatTotalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟踪号.
        /// </summary>
        public static string LogFormatTraceId {
            get {
                return ResourceManager.GetString("LogFormatTraceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string LogFormatUrl {
            get {
                return ResourceManager.GetString("LogFormatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作人编号.
        /// </summary>
        public static string LogFormatUserId {
            get {
                return ResourceManager.GetString("LogFormatUserId", resourceCulture);
            }
        }
    }
}
