// <auto-generated />
namespace CodeStudy.CodeFirst.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogNameMax : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogNameMax));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251348254_BlogNameMax"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
