// <auto-generated />
namespace CodeStudy.CodeFirst.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogAuthor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogAuthor));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251404194_BlogAuthor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
